
backend = "glx";
vsync = true;
use-damage = true;
shadow = true;
glx-swap-method = "exchange";
cache-size = 4096;

animations = (
    {
        triggers = [ "open", "show" ];
        preset = "slide-in";
        direction = "up";
        duration = 0.1;
    },
    {
        triggers = [ "close", "hide" ];
        preset = "slide-out";
        direction = "down";
        duration = 0.1;
    },
    {
        triggers = [ "geometry" ];
        preset = "geometry-change";
        duration = 0.1;
    }
);